
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: # username
  password: # password

development:
  <<: *default
  database: rakuten_challenge_development

test:
  <<: *default
  database: rakuten_challenge_test
